"""empty message

Revision ID: 46b0e068bd58
Revises: 
Create Date: 2019-08-12 21:50:14.103312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b0e068bd58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment',
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('experiment_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('experiment_id')
    )
    op.create_index(op.f('ix_experiment_experiment_name'), 'experiment', ['experiment_name'], unique=True)
    op.create_table('generated_image',
    sa.Column('volume_id', sa.Integer(), nullable=False),
    sa.Column('experiment_name', sa.String(length=128), nullable=True),
    sa.Column('volume_name', sa.String(length=256), nullable=True),
    sa.Column('sprite_b64', sa.Text(), nullable=True),
    sa.Column('sprite_json', sa.Text(), nullable=True),
    sa.Column('stat_map_b64', sa.Text(), nullable=True),
    sa.Column('colormap_b64', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_name'], ['experiment.experiment_name'], ),
    sa.PrimaryKeyConstraint('volume_id')
    )
    op.create_index(op.f('ix_generated_image_volume_name'), 'generated_image', ['volume_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_image_volume_name'), table_name='generated_image')
    op.drop_table('generated_image')
    op.drop_index(op.f('ix_experiment_experiment_name'), table_name='experiment')
    op.drop_table('experiment')
    # ### end Alembic commands ###
